apiVersion: v1
kind: Service
metadata:
  name: ezfastfood-catalog-service
spec:
  type: LoadBalancer # External communication
  selector:
    app: ezfastfood-catalog-ms
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
